converged: true
initial_cost_per_obs: 114420.43741988108
final_cost_per_obs: 8.2756745904492846
target_mount_to_target:
  x: 0.45762077694522135
  y: -0.11370916441218222
  z: 0.0058740466814854808
  qw: 0.99992860747484302
  qx: 0.0073818495406610283
  qy: -0.0090811423881081085
  qz: 0.0024126963562330962
camera_mount_to_camera:
  x: 0.03850114747059883
  y: -0.09268336808180952
  z: 0.071274308624225333
  qw: 0.65908927911113979
  qx: -0.2580729372317766
  qy: 0.65541579824670937
  qz: -0.26349537498398423
target_mount_to_target_rpy:
  x: 0.014721794186909009
  y: -0.018197612797208301
  z: 0.0046917709980415544
camera_mount_to_camera_rpy:
  x: 1.5819644105520236
  y: 2.3262610409212181
  z: 1.5737142986439765
target_mount_to_target_pos:
  x: 0.45762077694522135
  y: -0.11370916441218222
  z: 0.0058740466814854808
camera_mount_to_camera_pos:
  x: 0.03850114747059883
  y: -0.09268336808180952
  z: 0.071274308624225333